model_list:
  - model_name: Qwen/Qwen2.5-7B-Instruct
    litellm_params:
      model: openai/Qwen/Qwen2.5-7B-Instruct
      api_base: http://vllm:8000/v1
      api_key: EMPTY

  - model_name: Qwen/Qwen3.6-35B-A3B-FP8
    litellm_params:
      model: openai/Qwen/Qwen3.6-35B-A3B-FP8
      api_base: http://vllm:8000/v1
      api_key: EMPTY

  - model_name: Qwen/Qwen2.5-0.5B-Instruct
    litellm_params:
      model: openai/Qwen/Qwen2.5-0.5B-Instruct
      api_base: http://vllm:8000/v1
      api_key: EMPTY

router_settings:
  fallbacks:
    - Qwen/Qwen3.6-35B-A3B-FP8: ["Qwen/Qwen2.5-0.5B-Instruct", "Qwen/Qwen2.5-7B-Instruct"]
    - Qwen/Qwen2.5-7B-Instruct: ["Qwen/Qwen2.5-0.5B-Instruct", "Qwen/Qwen3.6-35B-A3B-FP8"]
    - Qwen/Qwen2.5-0.5B-Instruct: ["Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen3.6-35B-A3B-FP8"]

litellm_settings:
  drop_params: true
  set_verbose: false
